# Generated by Django 5.1.1 on 2024-10-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='user',
            new_name='created_by',
        ),
    ]
